### ISSUE TITLE
erase all things related to regional dexes

### ISSUE THREAD

**Issue by stygmaskyzoo** [stygmaskyzoo/project-untamed#17]
only one dex

**Comment by Shadowsoftime99** [comment]
[7ced858](https://github.com/stygmaskyzoo/project-untamed/commit/7ced858559061456ba8df014d97c1f4919f27267)

Removed everything that's not used in the PBS files, and the maps from the project. Just tried to trim a bunch of stuff basically. I commented out the stuff in trainerlists but left the files it's referencing, we could probably just delete all of those entirely?

Project does compile a lot faster! For now.

Things I'll do next: re-order internal IDs and thus cry/sprites to match, and remove unused cry/sprites. Maybe we can trim unused moves too

**Comment by Shadowsoftime99** [comment]
Also should mention that things are in the correct place in the in-game dex

**Comment by Shadowsoftime99** [comment]
All the in-world trainers (trainers.txt) I deleted except for the test trainers where I changed their Geodudes to Rockruff. The ones that are still around are like `littlecuptr` and `pokecuptr` and all those "cup" ones which are for the battle frontier. We're not making any type of battle facility, right?

**Comment by stygmaskyzoo** [comment]
not for the demo, can be erased too

**Comment by Shadowsoftime99** [comment]
Will delete those tomorrow then

**Comment by Shadowsoftime99** [comment]
Finished in b752ab8
