### ISSUE TITLE
only middle ball dissapears in starter selection

### ISSUE THREAD

**Issue by stygmaskyzoo** [stygmaskyzoo/project-untamed#21]
yep, its because of the plugin
probably has an easy fix

ar alternatively dont use pokeballs as overworld sprite

**Comment by Eva096** [comment]
It actually removes whichever ball you initially interact with to select a pokemon. If you want to make all 3 disappear after the starter is selected that should be pretty easy to do, I could also try to set it up so it removes the ball corresponding the pokemon you selected (from left to right: mollucotta, quetzalil, porsite)

**Comment by stygmaskyzoo** [comment]
> It actually removes whichever ball you initially interact with to select a pokemon. If you want to make all 3 disappear after the starter is selected that should be pretty easy to do, I could also try to set it up so it removes the ball corresponding the pokemon you selected (from left to right: mollucotta, quetzalil, porsite)

the correct dissapears because i fixed this yesterday but forgot to close the issue
thank you anyway!
