### ISSUE TITLE
turn all autotile paths being used into regular tileset tiles

### ISSUE THREAD

**Issue by stygmaskyzoo** [stygmaskyzoo/project-untamed#63]

**Comment by stygmaskyzoo** [comment]
@Gardenette why this change?

**Comment by Gardenette** [comment]
I thought that's what we wanted, to change the autotiles into regular tiles we can place on layer 1

**Comment by stygmaskyzoo** [comment]
nono autotiles work
we can have those on layer 1 too
i actually fixed that in cemetery recently

**Comment by Gardenette** [comment]
Oh nice! Sorry for the change then. I misunderstood
