### ISSUE TITLE
some shadows go over the main character and some dont

### ISSUE THREAD

**Issue by stygmaskyzoo** [stygmaskyzoo/project-untamed#91]

**Comment by Gardenette** [comment]
Where does this happen?

**Comment by stygmaskyzoo** [comment]
> Where does this happen?

![image](https://user-images.githubusercontent.com/73248181/185346591-9ea08f82-c2c8-4e44-9576-730ec0fdcdd5.png)
![image](https://user-images.githubusercontent.com/73248181/185346620-18f58d81-c3a5-4117-b9fa-fa10a0a6026e.png)

big trees
